@startmindmap
<style>
node {
    Padding 12
    Margin 3
    HorizontalAlignment center
    LineThickness 1.0

    RoundCorner 40
    MaximumWidth 100

}
:depth(0) {
    FontSize 30
    Shadowing 5.0
    LineThickness 2.0
}
:depth(1) {
    FontSize 15
}
:depth(2) {
    MaximumWidth None

}
</style>
caption Figure 1
title { Total Price: $535.0, Total Mass: 8.87 kg }
- <&home>Поход
-- <&rain>Снаряжение
---_ Спальник $30 1.1
---_ Гaмак $15 0.12
---_ Тент $15 0.12
---_ Тент-пончо $15 0.12
---_ <s>Каримат обычный $15 0.12</s>
---_ Коврик надувной $15 0.12
---_ Фонарь наголовный $15 0.3
---_ <s>Палатка $80 2.5</s>
---_ Веревка
++ <&book>Гаджеты
+++_ <s>Камера $100 0.3</s>
+++_ Смартфон 0.3
+++_ Ноутбук 1.0
+++_ <s>Мобильный штатив $20</s>
+++_ <s>Портативная солнечная панель $100 1.0</s>
+++_ <s>удлинитель</s>
+++_ <s>powerbank $200 0.2</s>

-- <&cloudy>Одежда
---_ Обувь $20 0.1
---_ Панама
---_ <s>Дождевик-тент $20 0.1</s>
---_ <s>Шапка $10 0.1</s>

-- посуды средство для огня $30 0.5
---_ Огниво
---_ Фильтр для воды $20 0.12
---_ Комплект посуды $20 0.12
-- Сумки
---_ Сумка на пояс $40 0.3
---_ Рюкзак $100 1.0

++ <s>Провиант 3.0</s>


++ <&wrench>Инструмент
+++_ Лопата соперская $30 0.5
+++_ Топор $30 1.0
+++_ Пила $30 1.0
+++_ Нож $40 0.4
+++_ сверло $50 0.5
+++_ <s>стамеска $50 0.4</s>
+++_ multitool $20 0.15

++ <&list>прочее
@endmindmap